export const STRING_SET = {
  BUTTON__READ_MORE: 'Baca selengkapnya',
  CHANNEL__MESSAGE_LIST__NOTIFICATION__ON: 'pada',
  CHANNEL__MESSAGE_LIST__NOTIFICATION__NEW_MESSAGE: 'pesan baru',
  CLASS_ARCHIVED_BANNER: 'Kamu tidak dapat mengirimkan pesan ke kelas ini, karena kelas telah diarsipkan',
  LABEL__OPERATOR: 'Guru',
  LABEL__DATE_TODAY: 'Hari ini',
  LABEL__DATE_YESTERDAY: 'Kemarin',
  LABEL__DAY_SUNDAY: 'Minggu',
  LABEL__DAY_MONDAY: 'Senin',
  LABEL__DAY_TUESDAY: 'Selasa',
  LABEL__DAY_WEDNESDAY: 'Rabu',
  LABEL__DAY_THURSDAY: 'Kamis',
  LABEL__DAY_FRIDAY: 'Jumat',
  LABEL__DAY_SATURDAY: 'Sabtu',
  LABEL__OTHERS: 'Lainnya',
  ROGU__MODAL__DELETE_MESSAGE__TITLE: 'Yakin kamu mau menghapus chat?',
  ROGU__MODAL__DELETE_MESSAGE__SUBTITLE: 'Chat yang telah kamu hapus tidak bisa dilihat dan diakses kembali',
  TOAST__MAX_FILE_SIZE_ERROR: 'Gagal terkirim, ukuran melebihi 10MB',
  MESSAGE_MENU__VIEW: 'Lihat Pesan',
  MESSAGE_MENU__VIEW_FILE: 'Lihat File',
  MESSAGE_MENU__VIEW_IMAGE: 'Lihat Foto',
  MESSAGE_MENU__VIEW_VIDEO: 'Lihat Video',
  MESSAGE_MENU__COPY: 'Salin',
  MESSAGE_MENU__REPLY: 'Balas',
  MESSAGE_MENU__EDIT: 'Edit',
  MESSAGE_MENU__RESEND: 'Kirim Ulang',
  MESSAGE_MENU__DELETE: 'Hapus',
};

export default STRING_SET;
